### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by ghost** [vazco/universe-react-bootstrap#4]
I have it installed - when I try ti import using the included syntax it says that bootstrap doesn't exist

Uncaught (in promise) [Universe Modules]: Trying to load module "/universe/react-bootstrap/index/main" that doesn't exist!
    Error loading /_modules_/packages/universe/react-bootstrap/index/main as "bootstrap" from /_modules_/app/both/components/Header/Header

**Comment by ihealthdavid** [comment]
Does updating to the latest universe:modules help?

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
