### ISSUE TITLE
Stopped working after upgrade to Meteor 1.2.1

### ISSUE THREAD

**Issue by celloudiallo** [vazco/universe-react-bootstrap#5]
Hi,

This was working fine until i update to Meteor 1.2.1
Now for all ReactBootstrap components i get error like this:
`ProgressBar(...): React component classes must extend React.Component.`+

You might need to update the ReactBootstrap to fix this issue. please refer to 
https://github.com/react-bootstrap/react-bootstrap/issues/1309

**Comment by Timonzimm** [comment]
+1

**Comment by applebya** [comment]
+1

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
