### ISSUE TITLE
_react2 = _interopRequireDefault(_react) undefined after commit d60312b "switch from browserify to bower"

### ISSUE THREAD

**Issue by ihealthdavid** [vazco/universe-react-bootstrap#7]
Hi @MacRusher great work on universe:modules. Color Wars was a great way to showcase your packaging system.

After commit d60312b2f1277adf6b8e77eebc575876e5501113 "switch from browserify to bower", I get the error:
`
W20160105-14:35:38.307(-5)? (STDERR) TypeError: Cannot read property 'PropTypes' of undefined
W20160105-14:35:38.307(-5)? (STDERR)     at Object._interopRequireDefault (packages/universe_react-bootstrap/bower_components/react-bootstrap/react-bootstrap.js:1074:1)
`

Line 1074:
`propTypes: {
        accordion: _react2['default'].PropTypes.bool,
`

A few definitions:
`
/\* 26 _/
/_**/ function(module, exports, **webpack_require**) {

```
/* eslint react/prop-types: [2, {ignore: "bsStyle"}] */
/* BootstrapMixin contains `bsStyle` type validation */

'use strict';

var _extends = __webpack_require__(16)['default'];

var _interopRequireDefault = __webpack_require__(2)['default'];

exports.__esModule = true;

var _react = __webpack_require__(22);

var _react2 = _interopRequireDefault(_react);
```

`

Here are my package versions:
- universe:modules@0.6.7
- universe:modules-compiler@1.0.5
- universe:react-bootstrap@0.24.2
- react@0.3.0
- react-meteor-data@0.2.4
- react-runtime@0.14.1_1
- react-runtime-dev@0.14.1
- react-runtime-prod@0.14.1

I've rolled back to commit 4e92851bc914498af6989a8bc192652606ceb0ba, as I am trying to use React 0.14 and React Bootstrap 0.28

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
