### ISSUE TITLE
React component classes must extend React.Component - Packages not loading in correct order? More than one React being loaded?

### ISSUE THREAD

**Issue by akinnee** [vazco/universe-react-bootstrap#8]
I'm not sure the cause, but when I try to render anything from ReactBootstrap I'm getting this error:

```
Warning: Panel(...): React component classes must extend React.Component.
warning @   warning.js:45
ReactCompositeComponentMixin.mountComponent @   ReactCompositeComponent.js:170
wrapper @   ReactPerf.js:66
ReactReconciler.mountComponent  @   ReactReconciler:37
ReactCompositeComponentMixin.mountComponent @   ReactCompositeComponent.js:225
wrapper @   ReactPerf.js:66
ReactReconciler.mountComponent  @   ReactReconciler:37
ReactCompositeComponentMixin.mountComponent @   ReactCompositeComponent.js:225
wrapper @   ReactPerf.js:66
ReactReconciler.mountComponent  @   ReactReconciler:37
mountComponentIntoNode  @   ReactMount.js:266
Mixin.perform   @   Transaction.js:136
batchedMountComponentIntoNode   @   ReactMount.js:282
Mixin.perform   @   Transaction.js:136
ReactDefaultBatchingStrategy.batchedUpdates @   ReactDefaultBatchingStrategy:62
batchedUpdates  @   ReactUpdates.js:94
ReactMount._renderNewRootComponent  @   ReactMount.js:476
wrapper @   ReactPerf.js:66
ReactMount._renderSubtreeIntoContainer  @   ReactMount.js:550
ReactMount.render   @   ReactMount.js:570
wrapper @   ReactPerf.js:66
(anonymous function)    @   QuickJoinApp.jsx:25
runStartupCallbacks @   startup_client.js:30
ready   @   startup_client.js:32
```

AND

```
Uncaught Error: Invariant Violation: Panel.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
invariant   @   invariant.js:39
ReactCompositeComponentMixin._renderValidatedComponent  @   ReactCompositeComponent.js:613
wrapper @   ReactPerf.js:66
ReactCompositeComponentMixin.mountComponent @   ReactCompositeComponent.js:220
wrapper @   ReactPerf.js:66
ReactReconciler.mountComponent  @   ReactReconciler:37
ReactCompositeComponentMixin.mountComponent @   ReactCompositeComponent.js:225
wrapper @   ReactPerf.js:66
ReactReconciler.mountComponent  @   ReactReconciler:37
ReactCompositeComponentMixin.mountComponent @   ReactCompositeComponent.js:225
wrapper @   ReactPerf.js:66
ReactReconciler.mountComponent  @   ReactReconciler:37
mountComponentIntoNode  @   ReactMount.js:266
Mixin.perform   @   Transaction.js:136
batchedMountComponentIntoNode   @   ReactMount.js:282
Mixin.perform   @   Transaction.js:136
ReactDefaultBatchingStrategy.batchedUpdates @   ReactDefaultBatchingStrategy:62
batchedUpdates  @   ReactUpdates.js:94
ReactMount._renderNewRootComponent  @   ReactMount.js:476
wrapper @   ReactPerf.js:66
ReactMount._renderSubtreeIntoContainer  @   ReactMount.js:550
ReactMount.render   @   ReactMount.js:570
wrapper @   ReactPerf.js:66
(anonymous function)    @   QuickJoinApp.jsx:25
runStartupCallbacks @   startup_client.js:30
ready   @   startup_client.js:32
```

**Comment by wizardbeard** [comment]
I'm getting the same exception:

Uncaught Error: Invariant Violation: Grid.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.invariant @ invariant.js:39ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:613wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:220wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler:37mountComponentIntoNode @ ReactMount.js:266Mixin.perform @ Transaction.js:136batchedMountComponentIntoNode @ ReactMount.js:282Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy:62batchedUpdates @ ReactUpdates.js:94ReactMount._renderNewRootComponent @ ReactMount.js:476wrapper @ ReactPerf.js:66ReactMount._renderSubtreeIntoContainer @ ReactMount.js:550ReactMount.render @ ReactMount.js:570wrapper @ ReactPerf.js:66newFn @ deprecated.js:38(anonymous function) @ writerduet-readthrough-plugin-react.jsx:5runStartupCallbacks @ startup_client.js:30ready @ startup_client.js:32

**Comment by akinnee** [comment]
I ended up making my own components. But now that Meteor 1.3 is out, we should be able to use the official ReactBootstrap module available on npm.

**Comment by sascha1337** [comment]
so no need this package anymore ? just include reactboostrap with npm meteor 1.3 ?

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
